### ISSUE TITLE
Similar plugins available?

### ISSUE THREAD

**Issue by pcav** [WMS-Engineering/AusMap#1]
Thanks for sharing your work. I remember a similar plugin, but I cannot find it in the repo now. Could you please check?
Sorry for bothering, but we are striving at reducing duplication to make life easier for users.

**Comment by Dan-Knott** [comment]
The plugin is based on the Kortforsyningen plugin by Septima. But the plugin centred around the danish government datasets. I met Mie from Septma at the QGIS conference in Nodebo and she suggested making a version for Australian users

**Comment by pcav** [comment]
IMHO this is suboptimal. It would be preferable to have one plugin with two settings, one for dk and one for oz. This would make collaboration easier, and allow easier addition of more countries.
Could you please explore this possibility, better if publicly on the mailing list?
Thanks.

**Comment by Dan-Knott** [comment]
I'll have a chat to Septima about the possibility, but i think this should be perused as separate plugin as the original Kortforsyningen plugin is named for the Danish data provider and unless the name is changed, will be very hard to promote to the Australian QGIS users.

I also have the intent to explore some of my own ideas though with future version of this plugin. I will definitely continue talking Septima to work towards a goal of a universal plugin, but i believe that will take quite a bit of time.

**Comment by pcav** [comment]
Of course, an eventual unified plugin should have a more generic name.
Thanks for exploring.
