### ISSUE TITLE
QGIS 3.6.0 has upgraded to python 3.7

### ISSUE THREAD

**Issue by nickoppen** [WMS-Engineering/AusMap#10]
Hi,

You might be across this already but the syntax changes in 3.x have rendered all 2.x code inoperable.

Error:

Couldn't load plugin 'AusMap-master' due to an error when calling its classFactory() method 

SyntaxError: invalid syntax 
Traceback (most recent call last):
  File "D:/Apps/qgis36/apps/qgis/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/nick6/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AusMap-master\__init__.py", line 34, in classFactory
    from .aus_map import AusMap
  File "D:/Apps/qgis36/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/nick6/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AusMap-master\aus_map.py", line 139
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.6.0-Noosa Noosa, 58734527ab 

Python Path:
D:/Apps/qgis36/apps/qgis/./python
C:/Users/nick6/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/nick6/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
D:/Apps/qgis36/apps/qgis/./python/plugins
D:\Apps\qgis36\bin\python37.zip
D:\Apps\qgis36\apps\Python37\DLLs
D:\Apps\qgis36\apps\Python37\lib
D:\Apps\qgis36\bin
D:\Apps\qgis36\apps\Python37
D:\Apps\qgis36\apps\Python37\lib\site-packages
D:\Apps\qgis36\apps\Python37\lib\site-packages\win32
D:\Apps\qgis36\apps\Python37\lib\site-packages\win32\lib
D:\Apps\qgis36\apps\Python37\lib\site-packages\Pythonwin
C:/Users/nick6/AppData/Roaming/QGIS/QGIS3\profiles\default/python
D:/nick6/Business/Idylway Venture/GIS

**Comment by WaterModellingSolutions** [comment]
Hi @nickoppen AusMap is now compatible for QGIS 3.6.0 please refer here: https://plugins.qgis.org/plugins/AusMap/

Thank you
