### ISSUE TITLE
Unable to install plugin Win 10 QGIS 2.18.9

### ISSUE THREAD

**Issue by malleeblue** [WMS-Engineering/AusMap#3]
I'm getting an error about authentication

No contact to the configuration at https://raw.githubusercontent.com/Dan-Knott/AusMap/master/About.htm. Exception: <urlopen error Tunnel connection failed: 407 Proxy Authentication Required>

Johanna

**Comment by Dan-Knott** [comment]
Hi Johanna,

I've just installed QGIS 2.18.13 on a new install of windows 10 and AusMap installs and works okay without any issues. I'm thinking there might be a network issue with your network blocking the AusMap internet connection.

**Comment by malleeblue** [comment]
Hi Daniel,

 

Thanks for getting back to me. I agree that it looks like a network issue. I still can’t use the plugin at work but can at home.

 

Can you define what the proxy settings should be so that I can use the plugin?

 

 

 

Johanna
