### ISSUE TITLE
An error has occurred while executing Python code: 

### ISSUE THREAD

**Issue by Nasreen2018** [WMS-Engineering/AusMap#8]
Hi There,

I am using QGIS version 2.18.16 with AusMap plugin and I am getting the following error when selecting any option under it.

Any suggestions?
---------------
An error has occurred while executing Python code: 

TypeError: arguments did not match any overloaded call:   QFileInfo(): too many arguments   QFileInfo(QString): argument 1 has unexpected type 'QDomNode'   QFileInfo(QFile): argument 1 has unexpected type 'QDomNode'   QFileInfo(QDir, QString): argument 1 has unexpected type 'QDomNode'   QFileInfo(QFileInfo): argument 1 has unexpected type 'QDomNode' 
----------------

**Comment by HamishWatson** [comment]
Just wondering if you found a fix for this? I have reinstalled AusMAP a number of times now.

Cheers

**Comment by djbiggs** [comment]
Getting the same error would be good to see a resolution.
